# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Configured by: iclementine(iclementine.outlook.com)

# Site settings
permalink: /:categories/:year/:month/:day/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "LICENSE.md", "Gemfile", "Gemfile.lock"]
title: Clementine's Blog
# ítagline: Site Tagline
name: Clementine Chan
author: Clementine
email: iclementine.outlook.com

# Set time zone
timezone: Asia/Shanghai

# Write an awesome description for your new site below. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
# A personal blog about python, latex and structure engineering.
description: > # this > means to ignore newlines until "baseurl:"
  Share some personal notes here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
github_username:  iclementine

# Build settings
# markdown: kramdown -> already included in GitHub settings
highlighter: rouge # or pygments or null

# GitHub settings
#github: [metadata] # ? what's this for
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  toc_levels: 1..3

#gems:
plugins:
  - jekyll-coffeescript
  - jekyll-paginate
